---
- hosts: all
  connection: local
  gather_facts: true

  vars_prompt:
    - name: username
      prompt: "username"
      private: no
    - name: password
      prompt: "password"
      private: yes

  vars:
    provider:
      ip_address: '{{ ip }}'
      username: '{{ username }}'
      password: '{{ password }}'

  tasks:
    - name: get interface info
      paloaltonetworks.panos.panos_op:
        provider: '{{ provider }}'
        cmd_is_xml: true
        cmd: <show><interface>all</interface></show>
      register: result

    - name: ansible native list of dictionaries merge
      ansible.builtin.set_fact:
        hwifnet: "{{ hwifnet | default([]) + [ (result.stdout | from_json).response.result.ifnet.entry | selectattr('name','equalto', item) | first | combine((result.stdout | from_json).response.result.hw.entry | selectattr('name','equalto', item) | first)] }}"
      loop: "{{ (result.stdout | from_json).response.result.ifnet.entry | map(attribute='name') | list }}"

    - name: debug
      ansible.builtin.debug:
        var: hwifnet

    - name: template out interfaces
      template:
        src: ipif.j2
        dest: output/interface_report.csv
        mode: 0644
      vars:
        interfaces: '{{ hwifnet }} '
